apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t01
  namespace: ygn40972
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: ygn40972
  destination:
    name: argus
    namespace: ygn40972
  source:
    path: apps
    repoURL: https://github.com/pjnaughton/t01-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
